/**
 * Silabus jalur mendalam: 10 modul x 10 pelajaran per bahasa (100 materi).
 * Tingkat menaik: dasar-plus -> menengah -> menengah-atas -> lanjut -> lapangan.
 * Fondasi (6 konsep inti) TIDAK diulang di sini; jalur ini mulai sedikit di atasnya.
 */

export type ModulSilabus = { judul: string; deskripsi: string; tingkat: string };

export const SILABUS: Record<string, ModulSilabus[]> = {
  python: [
    { judul: "Python yang Idiomatik", deskripsi: "Multiple assignment, walrus operator, f-string lanjut, None, truthiness, dan konvensi penamaan PEP 8.", tingkat: "dasar-plus" },
    { judul: "Koleksi Inti", deskripsi: "Comprehension, slicing lanjut, tuple, set, dict bercabang, dan kapan memakai struktur mana.", tingkat: "menengah" },
    { judul: "Fungsi dan Gaya Fungsional", deskripsi: "args/kwargs, default mutable pitfall, lambda, map/filter, closure, dan decorator dasar.", tingkat: "menengah" },
    { judul: "Error dan Exception", deskripsi: "try/except/else/finally, raise, exception chain, custom exception, dan prinsip EAFP.", tingkat: "menengah" },
    { judul: "Pemrograman Berorientasi Objek", deskripsi: "class, @property, dataclass, inheritance, dunder methods, dan komposisi.", tingkat: "menengah-atas" },
    { judul: "Modul, Paket, dan Lingkungan", deskripsi: "import system, struktur proyek, venv, pip, dan idiom if __name__ == __main__.", tingkat: "menengah-atas" },
    { judul: "File dan Data", deskripsi: "context manager, pathlib, csv, json, encoding, dan penanganan file besar.", tingkat: "lanjut" },
    { judul: "Stdlib yang Sering Dipakai Kerja", deskripsi: "datetime, collections, itertools, re, logging, dan argparse untuk CLI.", tingkat: "lanjut" },
    { judul: "Kode Rapi dan Teruji", deskripsi: "type hints, pytest dasar, enum, debugging, dan refactoring aman.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "Struktur aplikasi CLI yang rapi, HTTP dengan urllib/requests-style, konfigurasi, dan mini proyek akhir.", tingkat: "lapangan" },
  ],
  go: [
    { judul: "Go yang Idiomatik", deskripsi: "Tipe dasar, zero value, const/iota, multiple return, dan konvensi penamaan Go.", tingkat: "dasar-plus" },
    { judul: "Slice, Map, dan Array", deskripsi: "Anatomi slice (len/cap), append dan copy, map patterns, dan jebakan referensi.", tingkat: "menengah" },
    { judul: "Struct dan Method", deskripsi: "Struct, embedding, method pointer vs value, dan komposisi tanpa inheritance.", tingkat: "menengah" },
    { judul: "Interface dan Error", deskripsi: "Interface implisit, pola error, errors.Is/As/wrapping, panic/recover yang benar.", tingkat: "menengah-atas" },
    { judul: "Generics dan Pola Tipe", deskripsi: "Type parameters, constraints, dan kapan generics justru bikin rumit.", tingkat: "lanjut" },
    { judul: "Goroutine dan Channel", deskripsi: "Goroutine, buffered/unbuffered channel, select, dan WaitGroup.", tingkat: "lanjut" },
    { judul: "Sinkronisasi dan Pola Concurrent", deskripsi: "Mutex, atomic, worker pool, pipeline, fan-out/fan-in, dan context pembatalan.", tingkat: "lanjut" },
    { judul: "Stdlib Inti", deskripsi: "strings/strconv, time, os/io, encoding/json, dan testing bawaan.", tingkat: "lanjut" },
    { judul: "Modul dan Alat Kerja", deskripsi: "go mod, table-driven test, benchmark, go vet/fmt, dan struktur proyek.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "HTTP server dengan net/http, JSON API mini, graceful shutdown, dan mini proyek akhir.", tingkat: "lapangan" },
  ],
  c: [
    { judul: "Tipe dan Memori Dasar", deskripsi: "Ukuran tipe, cast, qualifier const/volatile, storage class, dan representasi angka.", tingkat: "dasar-plus" },
    { judul: "Pointer Secara Benar", deskripsi: "Aritmetika pointer, pointer vs array, pointer ke pointer, dan void*.", tingkat: "menengah" },
    { judul: "Memori Dinamis", deskripsi: "malloc/calloc/realloc/free, memory leak, dangling pointer, dan disiplin kepemilikan.", tingkat: "menengah" },
    { judul: "String dan Buffer", deskripsi: "char array, string.h, jebakan buffer overflow, dan kebiasaan aman.", tingkat: "menengah" },
    { judul: "Struct, Union, Enum", deskripsi: "struct, padding, typedef, union, enum, dan nested data.", tingkat: "menengah-atas" },
    { judul: "Fungsi Lanjut", deskripsi: "Function pointer, rekursi, variadic, dan organisasi header multi-file.", tingkat: "menengah-atas" },
    { judul: "Struktur Data di C", deskripsi: "Dynamic array, linked list, stack/queue, dan hash table sederhana.", tingkat: "lanjut" },
    { judul: "Preprocessor dan Build", deskripsi: "Macro, include guard, kompilasi multi-file, dan Makefile sederhana.", tingkat: "lanjut" },
    { judul: "File I/O", deskripsi: "fopen/fread/fwrite, file biner, EOF, dan penanganan error I/O.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "Parsing argv, struktur program besar, kebiasaan debugging, dan mini proyek akhir.", tingkat: "lapangan" },
  ],
  cpp: [
    { judul: "C++ Modern Sejak Awal", deskripsi: "Reference, auto, range-for, namespace, dan perbedaan penting dari C.", tingkat: "dasar-plus" },
    { judul: "Class dan Object", deskripsi: "Constructor/destructor, encapsulation, rule of three/five secara praktis.", tingkat: "menengah" },
    { judul: "STL Container", deskripsi: "vector, map, set, deque, stack, queue, dan memilih container yang tepat.", tingkat: "menengah" },
    { judul: "Algoritma dan Lambda", deskripsi: "sort/find/accumulate, iterator, lambda, dan compose logika tanpa loop manual.", tingkat: "menengah-atas" },
    { judul: "String dan Stream", deskripsi: "std::string, stringstream, file stream, dan parsing input teks.", tingkat: "menengah-atas" },
    { judul: "Memori dan Smart Pointer", deskripsi: "RAII, unique_ptr, shared_ptr, dan menghindari new/delete manual.", tingkat: "lanjut" },
    { judul: "Template Dasar", deskripsi: "Function/class template, auto return, dan constexpr sederhana.", tingkat: "lanjut" },
    { judul: "Error dan Ketahanan", deskripsi: "exception, std::optional, assert, dan desain API yang aman.", tingkat: "lanjut" },
    { judul: "Praktik Modern", deskripsi: "enum class, structured bindings, const correctness, dan idioma modern.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "Program multi-file dengan CMake/g++ sederhana, parsing data, dan mini proyek akhir.", tingkat: "lapangan" },
  ],
  java: [
    { judul: "Java yang Idiomatik", deskripsi: "Tipe primitif vs wrapper, var, immutable String, StringBuilder, dan konvensi.", tingkat: "dasar-plus" },
    { judul: "OOP Inti", deskripsi: "Class, encapsulation, static vs instance, this, constructor chaining, package.", tingkat: "menengah" },
    { judul: "Inheritance dan Polymorphism", deskripsi: "Abstract class, interface, overriding, super, dan desain dengan kontrak.", tingkat: "menengah" },
    { judul: "Collections Framework", deskripsi: "List/Set/Map, generics, equals/hashCode, Comparable/Comparator.", tingkat: "menengah-atas" },
    { judul: "Exception dan I/O", deskripsi: "Checked vs unchecked, try-with-resources, Files/Paths, dan desain error.", tingkat: "menengah-atas" },
    { judul: "Java Fungsional", deskripsi: "Lambda, functional interface, method reference, dan Optional.", tingkat: "lanjut" },
    { judul: "Streams API", deskripsi: "filter/map/reduce, Collectors, grouping, dan pipeline data yang bersih.", tingkat: "lanjut" },
    { judul: "Concurrency Dasar", deskripsi: "Thread, ExecutorService, synchronized, dan pola aman data bersama.", tingkat: "lanjut" },
    { judul: "Java Modern", deskripsi: "Record, sealed class, text block, switch expression, dan LocalDateTime.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "Struktur proyek, JUnit dasar, build jar, dan mini proyek akhir.", tingkat: "lapangan" },
  ],
  php: [
    { judul: "PHP yang Idiomatik", deskripsi: "Strict types, perbandingan == vs ===, coercion, null handling, dan konvensi.", tingkat: "dasar-plus" },
    { judul: "Array Secara Dalam", deskripsi: "Array asosiatif, map/filter/reduce, sorting, destructuring, dan referensi.", tingkat: "menengah" },
    { judul: "Fungsi dan Scope", deskripsi: "Default/variadic/nullable param, anonymous function, arrow function, use.", tingkat: "menengah" },
    { judul: "OOP Inti", deskripsi: "Class, visibility, static, constant, constructor property promotion.", tingkat: "menengah-atas" },
    { judul: "OOP Lanjut", deskripsi: "Interface, abstract class, trait, namespace, dan autoload.", tingkat: "menengah-atas" },
    { judul: "Error dan Exception", deskripsi: "try/catch/finally, custom exception, throwable hierarchy, dan logging.", tingkat: "lanjut" },
    { judul: "Web dan Request", deskripsi: "Superglobal GET/POST, validasi dan sanitasi, session, cookie, header.", tingkat: "lanjut" },
    { judul: "File, JSON, dan Data", deskripsi: "File I/O, json_encode/decode, csv, dan serialisasi aman.", tingkat: "lanjut" },
    { judul: "Composer dan Pengujian", deskripsi: "Composer, PSR-4 autoload, PHPUnit dasar, dan struktur proyek.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "Front controller sederhana, routing, hashing password, prepared statement konsep, mini proyek akhir.", tingkat: "lapangan" },
  ],
  csharp: [
    { judul: "C# yang Idiomatik", deskripsi: "Tipe dan var, string interpolation, nullable reference, pattern matching dasar.", tingkat: "dasar-plus" },
    { judul: "Collections dan Generics", deskripsi: "List/Dictionary/HashSet, generics, IEnumerable, dan comparator.", tingkat: "menengah" },
    { judul: "OOP Inti", deskripsi: "Class, property, access modifier, static, constructor, this.", tingkat: "menengah" },
    { judul: "OOP Lanjut dan Record", deskripsi: "Interface, inheritance, abstract, record, dan equality.", tingkat: "menengah-atas" },
    { judul: "Exception dan File I/O", deskripsi: "try/catch/finally, using statement, File/Directory, System.Text.Json.", tingkat: "menengah-atas" },
    { judul: "LINQ Inti", deskripsi: "Where/Select/OrderBy dengan method syntax, dan deferred execution.", tingkat: "lanjut" },
    { judul: "LINQ Lanjut dan Delegasi", deskripsi: "GroupBy/Join/aggregate, Func/Action, dan komposisi logika.", tingkat: "lanjut" },
    { judul: "Async dan Task", deskripsi: "async/await, Task, penanganan exception async, dan jebakan umum.", tingkat: "lanjut" },
    { judul: "Kode Rapi dan Teruji", deskripsi: "Naming, unit test konsep dengan assert, debugging, dan refactoring.", tingkat: "lanjut" },
    { judul: "Menuju Proyek Lapangan", deskripsi: "Program CLI multi-file, parsing argumen, konfigurasi, logging, dan mini proyek akhir.", tingkat: "lapangan" },
  ],
};
